from dataclasses import dataclass, field
from typing import Annotated, Literal, TypedDict

from langchain_core.documents import Document
from langchain_core.messages import AnyMessage
from langgraph.graph import add_messages

from utils.utils import reduce_docs
from pydantic import BaseModel, Field


@dataclass(kw_only=True)
class InputState:
    """Restricted input interface exposed to the outside world.

    Accepts the initial user message and nothing else, keeping the
    internal AgentState hidden from callers.
    """
    messages: Annotated[list[AnyMessage], add_messages]


class Router(TypedDict):
    """Classify user query."""
    logic: str
    type: Literal["more-info", "environmental", "general"]


class GradeHallucinations(BaseModel):
    """Binary score for hallucination present in the generated answer."""
    binary_score: str = Field(
        description="Answer is grounded in the facts, '1' or '0'"
    )


@dataclass(kw_only=True)
class AgentState(InputState):
    """Full internal state of the supervisor retrieval graph."""

    router: Router = field(default_factory=lambda: Router(type="general", logic=""))
    """The router's classification of the user's query."""

    steps: list[str] = field(default_factory=list)
    """Ordered list of research steps generated by the planner."""

    documents: Annotated[list[Document], reduce_docs] = field(default_factory=list)
    """Populated by the retriever — documents the agent can reference."""

    hallucination: GradeHallucinations = field(
        default_factory=lambda: GradeHallucinations(binary_score="0")
    )
    """Result of the hallucination check node."""
